---
title: "p8105_hw2_cx2227"
author: "Chuyue Xiang"
date: "10/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Problem 1

### Part1: Read and clean the Mr. Trash Wheel sheet
```{r}
trashwheel = read_excel("Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "Mr. Trash Wheel",
                        range = "A2:N406", na = "") %>%
  janitor::clean_names() %>%
  na.omit() %>% 
  mutate(sports_balls = as.integer(round(sports_balls, 0)))
```

### Part2: Read and clean precipitation data for 2017 and 2018

#### Read and clean 2017 precipitation data
```{r}
precip_2017 = read_excel("Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2017 Precipitation", 
                         range = "A2:B14", na = "" ) %>%
  mutate(year = 2017)
```


#### Read and clean 2018 precipiitation data
```{r}
precip_2018 = read_excel("Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2018 Precipitation", 
                         range = "A2:B14", na = "" ) %>%
  mutate (year = 2018)
```

#### Combine 2017 and 2018 data
```{r}
combine_precip = left_join(precip_2017, precip_2018, by = "Month") %>%
  mutate(Month = month.name)
```

